// <auto-generated />
namespace ProjectManagerDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addingtasktest1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingtasktest1));
        
        string IMigrationMetadata.Id
        {
            get { return "201910161056099_adding task test1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
