// <auto-generated />
namespace ProjectManagerDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class updatedchangedb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedchangedb));
        
        string IMigrationMetadata.Id
        {
            get { return "201910160858058_updated change db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
